/* stdin */
static void aptx_generate_dither(struct aptx_channel *channel);
static void aptx_qmf_tree_analysis(struct aptx_QMF_analysis *qmf, const int32_t samples[4], int32_t subband_samples[4]);
static void aptx_qmf_tree_synthesis(struct aptx_QMF_analysis *qmf, const int32_t subband_samples[4], int32_t samples[4]);
static void aptx_quantize_difference(struct aptx_quantize *quantize, int32_t sample_difference, int32_t dither, int32_t quantization_factor, const struct aptx_tables *tables);
static void aptx_encode_channel(struct aptx_channel *channel, const int32_t samples[4], int hd);
static void aptx_decode_channel(struct aptx_channel *channel, int32_t samples[4]);
static void aptx_invert_quantization(struct aptx_invert_quantize *invert_quantize, int32_t quantized_sample, int32_t dither, const struct aptx_tables *tables);
static int32_t *aptx_reconstructed_differences_update(struct aptx_prediction *prediction, int32_t reconstructed_difference, int order);
static void aptx_prediction_filtering(struct aptx_prediction *prediction, int32_t reconstructed_difference, int order);
static void aptx_process_subband(struct aptx_invert_quantize *invert_quantize, struct aptx_prediction *prediction, int32_t quantized_sample, int32_t dither, const struct aptx_tables *tables);
static void aptx_invert_quantize_and_prediction(struct aptx_channel *channel, int hd);
static int32_t aptx_quantized_parity(const struct aptx_channel *channel);
static int aptx_check_parity(const struct aptx_channel channels[NB_CHANNELS], uint8_t *sync_idx);
static void aptx_insert_sync(struct aptx_channel channels[NB_CHANNELS], uint8_t *sync_idx);
static uint16_t aptx_pack_codeword(const struct aptx_channel *channel);
static uint32_t aptxhd_pack_codeword(const struct aptx_channel *channel);
static void aptx_unpack_codeword(struct aptx_channel *channel, uint16_t codeword);
static void aptxhd_unpack_codeword(struct aptx_channel *channel, uint32_t codeword);
static void aptx_encode_samples(struct aptx_context *ctx, int32_t samples[NB_CHANNELS][4], uint8_t *output);
static int aptx_decode_samples(struct aptx_context *ctx, const uint8_t *input, int32_t samples[NB_CHANNELS][4]);
static void aptx_reset_decode_sync(struct aptx_context *ctx);
struct aptx_context *aptx_init(int hd);
void aptx_reset(struct aptx_context *ctx);
void aptx_finish(struct aptx_context *ctx);
size_t aptx_encode(struct aptx_context *ctx, const unsigned char *input, size_t input_size, unsigned char *output, size_t output_size, size_t *written);
int aptx_encode_finish(struct aptx_context *ctx, unsigned char *output, size_t output_size, size_t *written);
size_t aptx_decode(struct aptx_context *ctx, const unsigned char *input, size_t input_size, unsigned char *output, size_t output_size, size_t *written);
size_t aptx_decode_sync(struct aptx_context *ctx, const unsigned char *input, size_t input_size, unsigned char *output, size_t output_size, size_t *written, int *synced, size_t *dropped);
size_t aptx_decode_sync_finish(struct aptx_context *ctx);
